### ISSUE TITLE
Crash after scrolling up a few times and then back down

### ISSUE THREAD

**Issue by atroutt** [snipsnap/SlyceMessaging#1]
I had load more messages as it is in the sample code (loads 50 more each time) and after scrolling up a few times when I go to scroll back down I sometimes get a crash.

Here's the error:
```E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                            Process: com.audreytroutt.android.androidbeginnerchat, PID: 1103
                                                                                            java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1c2ac73 position=154 id=-1, oldPos=4, pLpos:4 scrap [attachedScrap] tmpDetached no parent}
                                                                                                at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4505)
                                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4636)
                                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                                                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                                                at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:549)
                                                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2979)
                                                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2904)
                                                                                                at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1482)
                                                                                                at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1519)
                                                                                                at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2486)
                                                                                                at android.view.View.dispatchTouchEvent(View.java:9297)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2549)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                                at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                                at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:2769)
                                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                                at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                                at android.view.View.dispatchPointerEvent(View.java:9517)
                                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4242)
                                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4108)
                                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
                                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
                                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
                                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3799)
                                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
                                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3856)
                                                                                            	at android.vi```

**Comment by MatthewPageCS** [comment]
I messed around with this area of the code a lot today. I can't replicate the error, so let's consider it solved for now.
