### ISSUE TITLE
Error about picasso method call from main thread

### ISSUE THREAD

**Issue by atroutt** [snipsnap/SlyceMessaging#2]
When I posted an image I noticed an error in the logs related to Picasso

```W/System.err: java.lang.IllegalStateException: Method call should not happen from the main thread.
W/System.err:     at com.squareup.picasso.Utils.checkNotMain(Utils.java:130)
W/System.err:     at com.squareup.picasso.RequestCreator.get(RequestCreator.java:383)
W/System.err:     at it.slyce.slyce_messaging.messenger.utils.Utils.getWidthToHeightRatio(Utils.java:19)
W/System.err:     at it.slyce.slyce_messaging.messenger.message.messageItem.master.media.MessageMediaItem.buildMessageItem(MessageMediaItem.java:41)
W/System.err:     at it.slyce.slyce_messaging.messenger.message.messageItem.MessageRecyclerAdapter.onBindViewHolder(MessageRecyclerAdapter.java:95)
W/System.err:     at it.slyce.slyce_messaging.messenger.message.messageItem.MessageRecyclerAdapter.onBindViewHolder(MessageRecyclerAdapter.java:26)```

**Comment by MatthewPageCS** [comment]
Solved - the method call was at the wrong step of the sequence.
